# --------------------------------------------------------AUTH
GET http://localhost:3001/activation/$2b$04$XCLIdmD.wVrylBkWWOM8T.
content-type: application/json
###
POST http://ec2-50-19-185-92.compute-1.amazonaws.com/api/auth/registration
content-type: application/json

{
  "email": "vladbuldenko@gmail.com",
  "password": "11111111",
  "repeatPassword": "11111111",
  "firstName": "V",
  "lastName": "B"
}
###
POST http://ec2-50-19-185-92.compute-1.amazonaws.com/api/auth/login
content-type: application/json

{
  "email": "bob.jones@example.com",
  "password": "bobspassword"
}
###

POST http://localhost:3001/forgotPassword
content-type: application/json

{
  "email": "vladbuldenko@gmail.com"
}
###
POST http://localhost:3001/resetPassword/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoidmxhZCIsImxhc3ROYW1lIjoiQnVsIiwiZW1haWwiOiJ2bGFkYnVsZGVua29AZ21haWwuY29tIiwiaWF0IjoxNzI1MDk3NDk5LCJleHAiOjE3MjUxMDEwOTl9.MB53R4GyrdTqRSzf8BMgLjw7t_mZCyEsi6wwQb1h5wI
content-type: application/json

{
  "password": "123456",
  "passwordConfirm": "123456"
}
###

# --------------------------------------------------------USERS
GET http://localhost:3001/users/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmY5NGEwYmI5MzMzNDAzNDZkYmFhZSIsImZpcnN0TmFtZSI6IlZsYWQiLCJsYXN0TmFtZSI6IkJ1bGRlbmtvIiwiZW1haWwiOiJ2bGFkYnVsZGVua29AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMxMTgxODkxLCJleHAiOjE3MzEyNjgyOTF9.Ki4IDT_GUfsPPerZyC7NBrgvWUzUS2_LuVIFPGEt1sM
###

# --------------------------------------------------------DISHES
POST http://localhost:3001/abonements
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MmY5NGEwYmI5MzMzNDAzNDZkYmFhZSIsImZpcnN0TmFtZSI6IlZsYWQiLCJsYXN0TmFtZSI6IkJ1bGRlbmtvIiwiZW1haWwiOiJ2bGFkYnVsZGVua29AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMxMTgxODkxLCJleHAiOjE3MzEyNjgyOTF9.Ki4IDT_GUfsPPerZyC7NBrgvWUzUS2_LuVIFPGEt1sM

{
  "clientId": "672f94a0bb933340346dbaae",
  "type": "group",
  "amount": "4",
  "price": "1700"
}
###
GET http://ec2-50-19-185-92.compute-1.amazonaws.com/api/dishes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJib2Iuam9uZXNAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzY5NDE3MjgsImV4cCI6MTczNjk0NDcyOH0.usxU2ZZSCqVUZ6EW8wShba-YQmOb2gGfGCes_DakjsdLNa0yE3R_LvB75yQXILn7
###

# --------------------------------------------------------TRAININGS
POST http://localhost:3001/trainings
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiSmFuZSIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJqYW5lLmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyNTQwMTA3MSwiZXhwIjoxNzI1NDg3NDcxfQ.G0dSFLglD067Qav1ZNlATs5l6RIm-wgPIdCN2AoOcg8

{
  "instructorId": 2,
  "type": "Stretching",
  "capacity": "8",
  "price": "1700",
  "day": "Monday",
  "time": "16:00",
  "date": "2024-09-02T17:22:22.961Z"
}
###
GET http://localhost:3001/trainings/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiSmFuZSIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJqYW5lLmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3MjUzOTk5NDAsImV4cCI6MTcyNTQ4NjM0MH0.Mlh65AGrvygxXeTpmHgnSjDZOVT0iF_8X6oiiN8reDw

###
PATCH  http://localhost:3001/trainings?abonementId=1&trainingId=1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3ROYW1lIjoiSmFuZSIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJqYW5lLmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyNTQ3OTY5NSwiZXhwIjoxNzI1NTY2MDk1fQ.4cNSVk4qrQAevpFJn-lePYL86eaF9coCMUzXUEE-LeY

{
  "updateType": "cancellation"
}
###