export enum Path {
  Home = "/",
  Services = "services",
  Schedule = "schedule-trainings",
  Prices = "prices",
  Contacts = "contacts",
  Login = "sign-in",
  SignUp = "sign-up",
  Restore = "/forgot-password",
  Reset = "/reset-password/:resetToken",
  Activate = "activate/:activationToken",
  ResetPassword = "reset-password",
  Account = "account",
  Purchases = "purchases",
  Users = "users",
  SelectedUser = "users/:id",
  Team = "team",
  Clients = "clients",
  Settings = "settings",
  CheckEmail = "check-email",
  ScheduleEditor = "schedule-editor",
}
